### ISSUE TITLE
Issues with installation process on Linux

### ISSUE THREAD

**Issue by N-0-N** [UNC0V3R3D/ChromeDecrypter#4]
I'm facing some issues when trying to install the ChromeDecrypter on Pop_OS/Kali Linux. After trying to install the requirements.txt the following error is shown:

"Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycryptodome==3.16.0 in /home/user/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (3.16.0)
ERROR: Could not find a version that satisfies the requirement pywin32==305 (from versions: none)
ERROR: No matching distribution found for pywin32==305"

I have also tried installing different versions of pywin32 on a Windows PC but it did not work. Since I couldn't find a solution to the issue, I would like to see some better explanation of the installation steps or a notice of  what I'm doing wrong. 

Thank you in advance.

**Comment by UNC0V3R3D** [comment]
This was developed for Windows only.
